name: push to ipfs
on:
  push:
    branches: [ main ]

#permissions:
#  contents: write
#  actions: write 
      
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}
      NEXT_PUBLIC_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      NEXT_PUBLIC_SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      NEXT_PUBLIC_SENTRY_PID: ${{ secrets.SENTRY_PID }}
      NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
      NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
      NEXT_PUBLIC_STORAGE_DEPOSIT_FEE: ${{ secrets.STORAGE_DEPOSIT_FEE }}
      NEXT_PUBLIC_CONTRACT_NAME: ${{ secrets.CONTRACT_NAME }}
      NEXT_PUBLIC_DEFAULT_NETWORK: ${{ secrets.DEFAULT_NETWORK }}
      #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Run Build & Export
        run: yarn build && yarn export
      - uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: "out"
      - run: echo ${{ steps.web3.outputs.cid }}
      - run: echo ${{ steps.web3.outputs.url }}
      - run: gh repo edit burrowfdn/burrow-cash --description ${{ steps.web3.outputs.url }}

