name: push to ipfs
on:
  push:
    branches: [ main ]

permissions:
  contents: write
      
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PID: ${{ secrets.SENTRY_PID }}
      POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
      POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
      STORAGE_DEPOSIT_FEE: ${{ secrets.STORAGE_DEPOSIT_FEE }}
      CONTRACT_NAME: ${{ secrets.CONTRACT_NAME }}
      DEFAULT_NETWORK: ${{ secrets.DEFAULT_NETWORK }}
      #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Run Build
        run: yarn build
      - uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: "public"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.web3.outputs.cid }}
      - run: echo ${{ steps.web3.outputs.url }}
      - run: gh repo edit burrowfdn/burrow-cash --description ${{ steps.web3.outputs.url }}

